name: Cd pipline

on:
  workflow_run:
    workflows: ["CI Pipline"]
    types:
      - completed
jobs:

  build:
    runs-on: self-hosted

    steps:
  
      - name: Pull Docker image
        run:  docker pull jonikrg/aws-test-python
        
      - name: Delete all docker cont
        run: docker rm -f aws-test-python-container || true
      
      - name: Docker run connt
        run: sudo docker run -d -p 8080:5000 --name aws-test-python-container jonikrg/aws-test-python
